In [7]:
%load_ext autoreload
# %autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
import logging
from sys import stdout
from datetime import datetime
import numpy as np
import os

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)

logging.info(f"{os.getlogin()}| {datetime.now()}")

[08-07 13:30:46][INFO] oscar| 2025-08-07 13:30:46.794490


In [9]:
import numpy as np

def gauss_jordan_inversa(A: np.ndarray) -> np.ndarray:
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)

    n = A.shape[0]
    assert A.shape[1] == n, "La matriz debe ser cuadrada."

    AI = np.hstack((A.copy(), np.identity(n)))

    for i in range(n):
        max_row = i + np.argmax(np.abs(AI[i:, i]))
        if AI[max_row, i] == 0:
            raise ValueError("La matriz no es invertible.")

        if max_row != i:
            AI[[i, max_row]] = AI[[max_row, i]]

        AI[i] = AI[i] / AI[i, i]

        for j in range(n):
            if j != i:
                AI[j] = AI[j] - AI[j, i] * AI[i]

    return AI[:, n:]

# Ejemplo de uso
A = [[2, -3], [-1, 1]]
A = np.array(A, dtype=float)

inversa = gauss_jordan_inversa(A)
print(inversa)


[[-1. -3.]
 [-1. -2.]]


In [10]:
%autoreload 2
from src import matriz_aumentada

A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
b = [1, -2, 3, 4]

Ab = matriz_aumentada(A, b)
gauss_jordan(Ab)

array([ 3., -6.,  6., -2.])

# Resolver

In [11]:
def gauss_jordan_inversa(A: np.ndarray) -> np.ndarray:
    """Calcula la inversa de una matriz cuadrada usando el método de Gauss-Jordan.

    ## Parameters
    ``A``: matriz cuadrada (n x n).

    ## Return
    ``A_inv``: matriz inversa de A.
    """
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)

    n = A.shape[0]
    assert A.shape[1] == n, "La matriz debe ser cuadrada."

    # Crear matriz aumentada [A | I]
    AI = np.hstack((A.copy(), np.identity(n)))

    for i in range(n):
        # Pivoteo parcial
        max_row = i + np.argmax(np.abs(AI[i:, i]))
        if AI[max_row, i] == 0:
            raise ValueError("La matriz no es invertible (columna con ceros).")

        # Intercambio de filas
        if max_row != i:
            AI[[i, max_row]] = AI[[max_row, i]]

        # Normalizar fila del pivote
        AI[i] = AI[i] / AI[i, i]

        # Eliminar otras filas en la columna
        for j in range(n):
            if j != i:
                AI[j] = AI[j] - AI[j, i] * AI[i]

    # Retornar la parte derecha (la inversa)
    A_inv = AI[:, n:]
    return A_inv


## Ejemplos
* Ejemplo 1

In [12]:
# La matriz A =
A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
# tiene como inversa
# A_inv =[[ 0.5, -0.5, -1.5,  1.5],
#        [-0.5,  1.5, -1.5,  0.5],
#        [-1.5, -1.5,  3.5, -1.5],
#        [ 1.5,  0.5, -1.5,  0.5]]
inv_matrix(A)

NameError: name 'inv_matrix' is not defined

* Ejemplo 2

In [ ]:
# La matriz A =
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]
# tiene como inversa
# A_inv =[[-34.,  31.,  52., -20.],
#         [ 19., -17., -29.,  11.],
#         [ 12., -11., -18.,   7.],
#         [  1.,  -1.,  -2.,   1.]]
inv_matrix(A)

## Ejercicios

* Ejercicio 1

In [13]:
A = [[2, -3], [-1, 1]]
gauss_jordan_inversa(A)

array([[-1., -3.],
       [-1., -2.]])

* Ejercicio 2

In [14]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
gauss_jordan_inversa(A)

array([[-36.,  45.,  60., -80.],
       [  3.,  -4.,  -5.,   7.],
       [  9., -11., -15.,  20.],
       [ 29., -36., -48.,  64.]])

* Ejercicio 3

In [ ]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
inv_matrix(A)

* Ejercicio 4

In [ ]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
inv_matrix(A)